package org.jcmpj.view;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jcmpj.controller.Docx;
import org.jcmpj.controller.IniciarAtualizacao;
import org.jcmpj.resources.Global;
import org.jcmpj.resources.WindowManager;

/**
 *
 * @author jcmpj
 */
public class MainWindow extends javax.swing.JFrame {

    WindowManager windowManager;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setIcon();
        windowManager = new WindowManager(desktopPane);
    }

    public void inicializar() {
        windowManager.openWindow(Listagem.getInstance());
        /**
         * Listagem laudos = new Listagem(); desktopPane.add(laudos);
         * laudos.setVisible(true);
         */
    }

    public void atualizarTabela() {
        Listagem listagem = Listagem.getInstance();
        listagem.LoadTable();
    }

    private void atualizarBancoDados() {
        boolean up;
        IniciarAtualizacao update_db = new IniciarAtualizacao();
        up = update_db.atualizar();
        if (up) {
            JOptionPane.showMessageDialog(null, "Banco de dados\natualizado", "Update!", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void saveAllWindows() {
        if (Listagem.getInstance().isVisible()) {
            Listagem.getInstance().saveAll();
        }
        if (Atividades.getInstance().isVisible()) {
            Atividades.getInstance().saveAll();
        }
        if (Acompanhantes.getInstance().isVisible()) {
            Acompanhantes.getInstance().saveAll();
        }
        if (Quesitos.getInstance().isVisible()) {
            Quesitos.getInstance().saveAll();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnAcompanhantes = new javax.swing.JButton();
        btnAtividades = new javax.swing.JButton();
        btnAbrirLaudo = new javax.swing.JButton();
        btnDadosBasicos = new javax.swing.JButton();
        btnQuesitos = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        arquivoMenu = new javax.swing.JMenu();
        alterarSenhaMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        laudosMenu = new javax.swing.JMenu();
        laudosMenuItem = new javax.swing.JMenuItem();
        atividadesMenuItem = new javax.swing.JMenuItem();
        acompanhantesMenuItem = new javax.swing.JMenuItem();
        atualizarMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        documentosMenu = new javax.swing.JMenu();
        abrirDocumentoMenuItem = new javax.swing.JMenuItem();
        sobreMenu = new javax.swing.JMenu();
        usuarioMenu = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de gerenciamento de Laudos Periciais Trabalhistas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 226));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dados do Laudo");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setForeground(new java.awt.Color(0, 51, 51));

        btnAcompanhantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAcompanhantes.setText("Acompanhantes");
        btnAcompanhantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcompanhantes.setEnabled(false);
        btnAcompanhantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcompanhantesActionPerformed(evt);
            }
        });

        btnAtividades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtividades.setText("Atividades");
        btnAtividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtividades.setEnabled(false);
        btnAtividades.setHideActionText(true);
        btnAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtividadesActionPerformed(evt);
            }
        });

        btnAbrirLaudo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAbrirLaudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/documento-32.png"))); // NOI18N
        btnAbrirLaudo.setText("Abrir Laudo");
        btnAbrirLaudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        btnAbrirLaudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbrirLaudo.setEnabled(false);
        btnAbrirLaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirLaudoActionPerformed(evt);
            }
        });

        btnDadosBasicos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDadosBasicos.setText("Dados Básicos");
        btnDadosBasicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDadosBasicos.setEnabled(false);
        btnDadosBasicos.setHideActionText(true);
        btnDadosBasicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosBasicosActionPerformed(evt);
            }
        });

        btnQuesitos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuesitos.setText("Quesitos");
        btnQuesitos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuesitos.setEnabled(false);
        btnQuesitos.setHideActionText(true);
        btnQuesitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuesitosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnQuesitos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDadosBasicos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtividades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAcompanhantes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnAbrirLaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDadosBasicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtividades)
                .addGap(12, 12, 12)
                .addComponent(btnAcompanhantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuesitos)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAbrirLaudo)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        arquivoMenu.setMnemonic('f');
        arquivoMenu.setText("Arquivo");

        alterarSenhaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/password_reset_icon.png"))); // NOI18N
        alterarSenhaMenuItem.setText("Alterar Senha");
        alterarSenhaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarSenhaMenuItemActionPerformed(evt);
            }
        });
        arquivoMenu.add(alterarSenhaMenuItem);

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/sair-32.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        arquivoMenu.add(exitMenuItem);

        menuBar.add(arquivoMenu);

        laudosMenu.setMnemonic('e');
        laudosMenu.setText("Laudos");

        laudosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/dados_basicos-02_icon.png"))); // NOI18N
        laudosMenuItem.setMnemonic('t');
        laudosMenuItem.setText("Dados básicos");
        laudosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laudosMenuItemActionPerformed(evt);
            }
        });
        laudosMenu.add(laudosMenuItem);

        atividadesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/labor_icon.png"))); // NOI18N
        atividadesMenuItem.setMnemonic('y');
        atividadesMenuItem.setText("Atividades");
        atividadesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividadesMenuItemActionPerformed(evt);
            }
        });
        laudosMenu.add(atividadesMenuItem);

        acompanhantesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/friends_icon.png"))); // NOI18N
        acompanhantesMenuItem.setText("Acompanhantes");
        acompanhantesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acompanhantesMenuItemActionPerformed(evt);
            }
        });
        laudosMenu.add(acompanhantesMenuItem);

        atualizarMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/data_table_icon_24.png"))); // NOI18N
        atualizarMenuItem.setMnemonic('p');
        atualizarMenuItem.setText("Recarregar banco atualizado");
        atualizarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarMenuItemActionPerformed(evt);
            }
        });
        laudosMenu.add(atualizarMenuItem);

        deleteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/database_import_icon_24.png"))); // NOI18N
        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Atualizar o banco de dados");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        laudosMenu.add(deleteMenuItem);

        menuBar.add(laudosMenu);

        documentosMenu.setText("Documentos");
        documentosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentosMenuActionPerformed(evt);
            }
        });

        abrirDocumentoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/documento-32.png"))); // NOI18N
        abrirDocumentoMenuItem.setText("Abrir Laudo");
        abrirDocumentoMenuItem.setEnabled(false);
        abrirDocumentoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirDocumentoMenuItemActionPerformed(evt);
            }
        });
        documentosMenu.add(abrirDocumentoMenuItem);

        menuBar.add(documentosMenu);

        sobreMenu.setMnemonic('h');
        sobreMenu.setText("Sobre");

        usuarioMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/user-01_icon.png"))); // NOI18N
        usuarioMenu.setMnemonic('c');
        usuarioMenu.setText("Usuário");
        usuarioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMenuActionPerformed(evt);
            }
        });
        sobreMenu.add(usuarioMenu);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jcmpj/view/images/about-1_icon.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Sobre");
        sobreMenu.add(aboutMenuItem);

        menuBar.add(sobreMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1250, 660));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        Object[] options = {"Salvar", "Sair sem salvar", "Cancelar"};
        int op;
        op = JOptionPane.showOptionDialog(null, "Salvar Dados?", "Operação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        System.out.println("Op Selecionada: " + op);
        if (op == 0) {
            saveAllWindows();
            System.exit(0);
        } else if (op == 1) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void laudosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laudosMenuItemActionPerformed
        windowManager.openWindow(Listagem.getInstance());
    }//GEN-LAST:event_laudosMenuItemActionPerformed

    private void atividadesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividadesMenuItemActionPerformed
        windowManager.openWindow(Atividades.getInstance());
    }//GEN-LAST:event_atividadesMenuItemActionPerformed

    private void atualizarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarMenuItemActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_atualizarMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        atualizarBancoDados();
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void documentosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentosMenuActionPerformed

    }//GEN-LAST:event_documentosMenuActionPerformed

    private void abrirDocumentoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirDocumentoMenuItemActionPerformed
        try {
            Docx.gerarDocumento();
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirDocumentoMenuItemActionPerformed

    private void acompanhantesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acompanhantesMenuItemActionPerformed
        windowManager.openWindow(Acompanhantes.getInstance());
    }//GEN-LAST:event_acompanhantesMenuItemActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        windowManager.openWindow(Acompanhantes.getInstance());
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtividadesActionPerformed
        windowManager.openWindow(Atividades.getInstance());
    }//GEN-LAST:event_btnAtividadesActionPerformed

    private void btnAcompanhantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcompanhantesActionPerformed
        windowManager.openWindow(Acompanhantes.getInstance());
    }//GEN-LAST:event_btnAcompanhantesActionPerformed

    private void btnAbrirLaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirLaudoActionPerformed
        try {
            Docx.gerarDocumento();
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAbrirLaudoActionPerformed

    private void btnDadosBasicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosBasicosActionPerformed
        windowManager.openWindow(Listagem.getInstance());
    }//GEN-LAST:event_btnDadosBasicosActionPerformed

    private void btnQuesitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuesitosActionPerformed
        windowManager.openWindow(Quesitos.getInstance());
    }//GEN-LAST:event_btnQuesitosActionPerformed

    private void usuarioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMenuActionPerformed
        DadosUsuario dadosUsuario = new DadosUsuario(this, true);
        Color backColor = new Color(254, 254, 254);
        dadosUsuario.getContentPane().setBackground(backColor);
        String cpf = Global.getUserName();
        dadosUsuario.lblCPF.setText(cpf);
        dadosUsuario.lblNOME.setText(Global.getName());

        /**
         * Formatar para apresentação a data de validade(expiração) da licença
         */
        String validade = Global.getPerExpires();
        String[] amd = validade.split("-");
        String dia = amd[2];
        String mes = amd[1];
        String ano = amd[0];
        String dma = dia + "/" + mes + "/" + ano;
        dadosUsuario.lblVALID.setText(dma);

        dadosUsuario.lblSERIAL.setText(Global.getSerial());
        dadosUsuario.setVisible(true);
    }//GEN-LAST:event_usuarioMenuActionPerformed

    private void alterarSenhaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarSenhaMenuItemActionPerformed
        AlterarSenha as = new AlterarSenha(this, true);
        as.setVisible(true);
    }//GEN-LAST:event_alterarSenhaMenuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Object[] options = {"Salvar", "Sair sem salvar", "Cancelar"};
        int op;
        op = JOptionPane.showOptionDialog(null, "Salvar Dados?", "Operação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        System.out.println("Op Selecionada: " + op);
        if (op == 0) {
            saveAllWindows();
            System.exit(0);
        } else if (op == 1) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    public static javax.swing.JMenuItem abrirDocumentoMenuItem;
    private javax.swing.JMenuItem acompanhantesMenuItem;
    private javax.swing.JMenuItem alterarSenhaMenuItem;
    private javax.swing.JMenu arquivoMenu;
    private javax.swing.JMenuItem atividadesMenuItem;
    private javax.swing.JMenuItem atualizarMenuItem;
    public static javax.swing.JButton btnAbrirLaudo;
    public static javax.swing.JButton btnAcompanhantes;
    public static javax.swing.JButton btnAtividades;
    public static javax.swing.JButton btnDadosBasicos;
    public static javax.swing.JButton btnQuesitos;
    private javax.swing.JMenuItem deleteMenuItem;
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu documentosMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu laudosMenu;
    private javax.swing.JMenuItem laudosMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu sobreMenu;
    private javax.swing.JMenuItem usuarioMenu;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/org/jcmpj/view/images/ico-jc.png")));
    }

}
